"""Runtime-configurable settings.

Two groups of settings are exposed to the UI, both persisted in the
``system_settings`` key/value table and pushed into ``app.config.settings``
at startup and on every PUT so the rest of the app sees changes without
a restart:

1. **Credentials** — LLM endpoint base URL and (optional) API key.
2. **Models** — writer and reviewer model IDs.

``AVAILABLE_MODELS`` is the authoritative list of models verified to work
against the configured endpoint. Re-probe it if the upstream catalog changes.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_tenant
from app.config import settings
from app.db.base import get_db
from app.db.models import SystemSetting, Tenant

router = APIRouter(prefix="/api/settings", tags=["settings"])


# Available-model catalog
# ----------------------------------------------------------------------------
# Source of truth is ``docs/llm-models.json``, regenerated by
# ``scripts/probe_llm_models.py`` — it posts a real request to every model in
# the endpoint's ``/v1/models`` list and marks each ``ok: true/false``. We
# expose all working entries. Re-probe whenever the upstream catalog drifts.
#
# The in-module fallback list below is used if the sidecar is missing or
# malformed (e.g. fresh clone before anyone's run the probe yet).

_PROBE_SIDECAR = (
    Path(__file__).resolve().parent.parent.parent.parent
    / "docs"
    / "llm-models.json"
)


def _family_from_id(model_id: str) -> str:
    """``oci/openai.gpt-5.4`` → ``openai``; first token after optional namespace."""
    stripped = model_id.split("/", 1)[-1]
    return stripped.split(".", 1)[0] if "." in stripped else stripped


def _is_reasoning(model_id: str) -> bool:
    """Reasoning-family models need ``max_completion_tokens``.

    Mirrors the classifier in ``app.gateway.llm_client._is_reasoning_model``
    with broader coverage for Llama Stack's ``-reasoning`` suffix convention
    (e.g. xAI's ``grok-4.20-reasoning`` / ``grok-4.20-non-reasoning`` split).
    """
    mid = model_id.lower()
    if "-non-reasoning" in mid:
        return False
    if "-reasoning" in mid:
        return True
    return any(tok in mid for tok in (".gpt-5", ".o1", ".o3", ".o4"))


def _label_from_id(model_id: str) -> str:
    """Best-effort human label from the model ID."""
    short = model_id.split("/", 1)[-1].split(".", 1)[-1]
    return short  # raw ID is already readable for these names


def _load_available_models() -> list[dict]:
    """Read the working-model list from the probe sidecar; fall back to a
    small curated default if the file isn't present yet."""
    if _PROBE_SIDECAR.exists():
        try:
            raw = json.loads(_PROBE_SIDECAR.read_text())
            out: list[dict] = []
            for r in raw:
                if not r.get("ok"):
                    continue
                mid = r["id"]
                out.append({
                    "id": mid,
                    "family": _family_from_id(mid),
                    "label": _label_from_id(mid),
                    "reasoning": _is_reasoning(mid),
                })
            # Keep deterministic order: family → label
            out.sort(key=lambda m: (m["family"], m["label"]))
            return out
        except Exception:  # noqa: BLE001 — fall back to curated list
            pass

    # Conservative fallback (covers the writer/reviewer defaults in config.py)
    return [
        {"id": "oci/openai.gpt-5.4",       "family": "openai", "label": "gpt-5.4",       "reasoning": True},
        {"id": "oci/openai.gpt-5.4-mini",  "family": "openai", "label": "gpt-5.4-mini",  "reasoning": True},
        {"id": "oci/openai.gpt-4.1",       "family": "openai", "label": "gpt-4.1"},
        {"id": "oci/openai.gpt-4.1-mini",  "family": "openai", "label": "gpt-4.1-mini"},
    ]


AVAILABLE_MODELS: list[dict] = _load_available_models()
_AVAILABLE_IDS = {m["id"] for m in AVAILABLE_MODELS}

# Keys persisted in the system_settings table. Mirrored onto ``settings`` in
# memory at startup and after each PUT. Legacy OCI_GENAI_* keys are ignored
# if still present in the table (safe; just stale rows).
_PERSISTED_KEYS = (
    "LLM_API_KEY",
    "LLM_BASE_URL",
    "LLM_WRITER_MODEL",
    "LLM_REVIEWER_MODEL",
    "LLM_ORCHESTRATOR_MODEL",
)


def _mask_api_key(key: str) -> str:
    """Return a UI-safe rendering of an API key.

    We only ever hand the last 4 characters back to the frontend so the
    plaintext secret never leaves the backend after it's been saved.
    """
    if not key:
        return ""
    if len(key) <= 8:
        return "••••"
    return f"{key[:3]}••••{key[-4:]}"


def _utcnow_sentinel() -> datetime:
    return datetime.utcnow()


async def _persist(db: AsyncSession, key: str, value: str) -> None:
    stmt = pg_insert(SystemSetting).values(key=key, value=value)
    stmt = stmt.on_conflict_do_update(
        index_elements=["key"],
        set_={"value": value, "updated_at": _utcnow_sentinel()},
    )
    await db.execute(stmt)


async def _load_persisted_overrides(db: AsyncSession) -> None:
    """Copy persisted settings (if any) onto the in-memory ``settings`` object.

    Called on startup (from ``app.main.lifespan``) and on each settings GET
    so the UI always reflects reality.
    """
    rows = (await db.execute(select(SystemSetting))).scalars().all()
    by_key = {r.key: r.value for r in rows}
    for k in _PERSISTED_KEYS:
        if k in by_key and by_key[k]:
            setattr(settings, k, by_key[k])


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------
class ModelSettings(BaseModel):
    writer_model: str
    reviewer_model: str
    # Reserved for future use — today the orchestrator is Python code, not
    # an LLM. Kept so saved DB values still round-trip.
    orchestrator_model: str | None = None


class ModelSettingsResponse(ModelSettings):
    available: list[dict]


@router.get("/models", response_model=ModelSettingsResponse)
async def get_model_settings(
    tenant: Tenant = Depends(get_current_tenant),
    db: AsyncSession = Depends(get_db),
):
    await _load_persisted_overrides(db)
    return ModelSettingsResponse(
        writer_model=settings.LLM_WRITER_MODEL,
        reviewer_model=settings.LLM_REVIEWER_MODEL,
        orchestrator_model=settings.LLM_ORCHESTRATOR_MODEL,
        available=AVAILABLE_MODELS,
    )


@router.put("/models", response_model=ModelSettingsResponse)
async def update_model_settings(
    body: ModelSettings,
    tenant: Tenant = Depends(get_current_tenant),
    db: AsyncSession = Depends(get_db),
):
    for name, val in (("writer_model", body.writer_model),
                      ("reviewer_model", body.reviewer_model)):
        if val not in _AVAILABLE_IDS:
            raise HTTPException(
                status_code=400,
                detail=f"{name} {val!r} is not in the list of available models",
            )
    if body.orchestrator_model is not None and body.orchestrator_model not in _AVAILABLE_IDS:
        raise HTTPException(
            status_code=400,
            detail=f"orchestrator_model {body.orchestrator_model!r} is not available",
        )

    await _persist(db, "LLM_WRITER_MODEL", body.writer_model)
    await _persist(db, "LLM_REVIEWER_MODEL", body.reviewer_model)
    if body.orchestrator_model is not None:
        await _persist(db, "LLM_ORCHESTRATOR_MODEL", body.orchestrator_model)
        settings.LLM_ORCHESTRATOR_MODEL = body.orchestrator_model
    await db.commit()

    settings.LLM_WRITER_MODEL = body.writer_model
    settings.LLM_REVIEWER_MODEL = body.reviewer_model

    return ModelSettingsResponse(
        writer_model=settings.LLM_WRITER_MODEL,
        reviewer_model=settings.LLM_REVIEWER_MODEL,
        orchestrator_model=settings.LLM_ORCHESTRATOR_MODEL,
        available=AVAILABLE_MODELS,
    )


# ---------------------------------------------------------------------------
# Credentials
# ---------------------------------------------------------------------------
class CredentialsResponse(BaseModel):
    """What the frontend sees.

    ``api_key_masked`` is a cosmetic fingerprint — the full value never leaves
    the backend once saved. ``api_key_set`` tells the UI whether to render a
    "Replace key" affordance vs an empty input. ``api_key_required`` is true
    when the configured endpoint rejects anonymous calls; when false, an
    empty key is fine (e.g., the internal Llama Stack gateway).
    """
    base_url: str
    api_key_masked: str
    api_key_set: bool


class CredentialsUpdate(BaseModel):
    # api_key is optional — leave blank to keep the existing one.
    api_key: str | None = None
    base_url: str


class CredentialsTestRequest(BaseModel):
    """Partial-override body for the test endpoint.

    All fields are optional — any missing/blank field falls back to the
    currently saved credentials. Lets the UI probe either the live config
    (post with empty body) or a candidate edit (post with the dirty form
    values) without juggling two endpoints.
    """
    api_key: str | None = None
    base_url: str | None = None


class TestResult(BaseModel):
    ok: bool
    error: str | None = None
    model_tested: str | None = None
    latency_ms: int | None = None


@router.get("/credentials", response_model=CredentialsResponse)
async def get_credentials(
    tenant: Tenant = Depends(get_current_tenant),
    db: AsyncSession = Depends(get_db),
):
    await _load_persisted_overrides(db)
    return CredentialsResponse(
        base_url=settings.LLM_BASE_URL,
        api_key_masked=_mask_api_key(settings.LLM_API_KEY),
        api_key_set=bool(settings.LLM_API_KEY),
    )


@router.put("/credentials", response_model=CredentialsResponse)
async def update_credentials(
    body: CredentialsUpdate,
    tenant: Tenant = Depends(get_current_tenant),
    db: AsyncSession = Depends(get_db),
):
    """Update LLM endpoint + API key. Only replaces the API key if
    ``api_key`` is a non-empty string — leave blank to keep existing. The
    API key is optional altogether (anonymous endpoints are supported)."""
    if not body.base_url.strip():
        raise HTTPException(status_code=400, detail="base_url is required")

    await _persist(db, "LLM_BASE_URL", body.base_url.strip())
    settings.LLM_BASE_URL = body.base_url.strip()

    if body.api_key is not None:
        new_key = body.api_key.strip()
        # Allow explicit clearing by passing an empty string.
        await _persist(db, "LLM_API_KEY", new_key)
        settings.LLM_API_KEY = new_key

    await db.commit()

    return CredentialsResponse(
        base_url=settings.LLM_BASE_URL,
        api_key_masked=_mask_api_key(settings.LLM_API_KEY),
        api_key_set=bool(settings.LLM_API_KEY),
    )


@router.post("/credentials/test", response_model=TestResult)
async def test_credentials(
    body: CredentialsTestRequest | None = None,
    tenant: Tenant = Depends(get_current_tenant),
    db: AsyncSession = Depends(get_db),
):
    """Make a tiny chat completion against the candidate credentials.

    Any field present in ``body`` overrides the currently saved value;
    anything omitted (or blank) falls back to what's configured. Nothing
    is persisted — ``/credentials`` PUT is the only write path.
    """
    await _load_persisted_overrides(db)

    api_key = (body.api_key.strip() if body and body.api_key else "") or settings.LLM_API_KEY
    base_url = (body.base_url.strip() if body and body.base_url else "") or settings.LLM_BASE_URL
    model = settings.LLM_REVIEWER_MODEL or settings.LLM_WRITER_MODEL

    if not base_url:
        return TestResult(ok=False, error="No base_url configured.")

    import time
    from openai import OpenAI
    from app.gateway.llm_client import _is_reasoning_model
    try:
        probe = OpenAI(api_key=api_key or "anonymous", base_url=base_url)
        t0 = time.perf_counter()
        params = {"model": model, "messages": [{"role": "user", "content": "ping"}]}
        # Reasoning models reject max_tokens
        params["max_completion_tokens" if _is_reasoning_model(model) else "max_tokens"] = 200
        resp = probe.chat.completions.create(**params)
        dur_ms = int((time.perf_counter() - t0) * 1000)
        txt = (resp.choices[0].message.content or "").strip()
        if not txt and resp.choices[0].finish_reason != "stop":
            return TestResult(
                ok=False,
                error=f"Empty response (finish_reason={resp.choices[0].finish_reason})",
                model_tested=model,
                latency_ms=dur_ms,
            )
        return TestResult(ok=True, model_tested=model, latency_ms=dur_ms)
    except Exception as exc:  # noqa: BLE001 — surface to UI
        return TestResult(ok=False, error=str(exc)[:500])
